//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBookingService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultSettings_Table
    {
        public long SrNo { get; set; }
        public Nullable<System.DateTime> LastAppUpdateDate { get; set; }
    }
}
