//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Linq;

namespace FlightBookingService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookMyFlightEntities : DbContext
    {
        public BookMyFlightEntities()
            : base("name=BookMyFlightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual IQueryable<AirlinesMaster_Tables> AirlinesMaster_Tables { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<DefaultSettings_Table> DefaultSettings_Table { get; set; }
        public virtual DbSet<FoodTypes_Table> FoodTypes_Table { get; set; }
        public virtual DbSet<RecentSearches_Table> RecentSearches_Table { get; set; }
        public virtual DbSet<TravelDestMaster_Table> TravelDestMaster_Table { get; set; }
        public virtual DbSet<Travellers_Table> Travellers_Table { get; set; }
        public virtual DbSet<User_Table> User_Table { get; set; }
        public virtual DbSet<UserBookings_Table> UserBookings_Table { get; set; }
        public virtual DbSet<UserBookingsDetails_Table> UserBookingsDetails_Table { get; set; }
    }
}
