//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBookingService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecentSearches_Table
    {
        public int Id { get; set; }
        public string TripType { get; set; }
        public string FromDest { get; set; }
        public string ToDest { get; set; }
        public System.DateTime DepartDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public double Fare { get; set; }
        public System.DateTime Add_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public bool Active { get; set; }
    }
}
