//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightBookingService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBookings_Table
    {
        public int Id { get; set; }
        public long User_ID { get; set; }
        public long Depart_AirlinesID { get; set; }
        public Nullable<long> Return_AirlinesID { get; set; }
        public string Depart_FlightNo { get; set; }
        public string Return_FlightNo { get; set; }
        public System.DateTime Book_Date { get; set; }
        public System.DateTime Departure_DateTime { get; set; }
        public System.DateTime Departure_ArrivalDateTime { get; set; }
        public Nullable<System.DateTime> Return_DateTime { get; set; }
        public Nullable<System.DateTime> Return_ArrivalDateTime { get; set; }
        public Nullable<long> From_DestID { get; set; }
        public Nullable<long> To_DestID { get; set; }
        public string Class { get; set; }
        public double Depart_AdultFare { get; set; }
        public Nullable<double> Return_AdultFare { get; set; }
        public double Departure_Fare { get; set; }
        public Nullable<double> Return_Fare { get; set; }
        public double Total_Fare { get; set; }
        public int Adult { get; set; }
        public Nullable<int> Child { get; set; }
        public Nullable<int> Infant { get; set; }
        public System.DateTime Add_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public Nullable<System.DateTime> Cancel_Date { get; set; }
        public bool Active { get; set; }
    }
}
